version: '3'

vars:
  VHOST_PATH: ./web

tasks:
  start:
    desc: Build les conteneurs web et db
    cmds:
      - docker compose up --build -d web db

  stop:
    desc: Arrête et supprime les conteneurs + volumes
    cmds:
      - docker compose down -v
      - sudo rm -rf ./db_data
      - docker builder prune -f

  restart:
    cmds:
      - docker compose restart web

  rebuild-all:
    desc: Rebuild complet avec certbot
    cmds:
      - task: stop
      - task: start

  composer-install:
    dir: ./app
    cmds:
      - composer install

  load-db:
    desc: Recharge la base MySQL depuis db_dump (DESTRUCTIF)
    cmds:
      - docker compose down
      - rm -rf ./db_data/*
      - docker compose up -d db
      - docker logs -f ubbc-mysql